<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <AssemblyName>Vyatka.Domain</AssemblyName>
        <RootNamespace>Vyatka.Domain</RootNamespace>
    </PropertyGroup>

</Project>
