// <auto-generated />
using System;
using System.Collections.Generic;
using Hub.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Hub.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(HubDbContext))]
    [Migration("20260721185305_AddedGoalTaskAssignments")]
    partial class AddedGoalTaskAssignments
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Hub.Domain.Events.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "DatesRange", "Hub.Domain.Events.Event.DatesRange#DatesRange", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<DateTimeOffset>("EndDate")
                                .HasColumnType("timestamp with time zone");

                            b1.Property<DateTimeOffset>("StartDate")
                                .HasColumnType("timestamp with time zone");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Description", "Hub.Domain.Events.Event.Description#RichText", b1 =>
                        {
                            b1.Property<string>("Format")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Text")
                                .IsRequired()
                                .HasColumnType("text");
                        });

                    b.HasKey("Id");

                    b.HasIndex("State");

                    b.ToTable("event", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Events.EventLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Coordinates", "Hub.Domain.Events.EventLocation.Coordinates#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");
                        });

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .IsUnique();

                    b.ToTable("event_location", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Events.EventRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsSealed")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("EventId", "Name")
                        .IsUnique();

                    b.ToTable("event_role", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Events.Goals.EventGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("event_goal", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Events.Goals.EventGoalTask", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GoalId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("GoalId");

                    b.ToTable("event_goal_task", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Events.Goals.EventGoalTaskAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantAssignmentId");

                    b.HasIndex("TaskId");

                    b.ToTable("event_goal_task_assignment", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Events.Participants.EventParticipant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("UserId");

                    b.HasIndex("EventId", "UserId")
                        .IsUnique();

                    b.ToTable("event_participant", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Events.Participants.EventParticipantRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParticipantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ParticipantId");

                    b.HasIndex("RoleId");

                    b.HasIndex("RoleId", "ParticipantId")
                        .IsUnique();

                    b.ToTable("event_participant_role", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("event_requirement", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirementAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssignParticipantId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("AssignParticipantId");

                    b.HasIndex("RequirementId");

                    b.ToTable("event_requirement_assignment", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirementVerification", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("RequirementAssignmentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("VerifierId")
                        .HasColumnType("uuid");

                    b.Property<string>("verification_type")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.HasKey("Id");

                    b.HasIndex("RequirementAssignmentId");

                    b.HasIndex("VerifierId");

                    b.ToTable("event_requirement_verification", (string)null);

                    b.HasDiscriminator<string>("verification_type").HasValue("EventRequirementVerification");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirementVerifier", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<Guid>("RequirementId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("verifier_type")
                        .IsRequired()
                        .HasMaxLength(34)
                        .HasColumnType("character varying(34)");

                    b.HasKey("Id");

                    b.HasIndex("RequirementId");

                    b.ToTable("event_requirement_verifier", (string)null);

                    b.HasDiscriminator<string>("verifier_type").HasValue("EventRequirementVerifier");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Hub.Domain.Groups.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("group", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Groups.GroupEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("GroupId");

                    b.HasIndex("GroupId", "EventId")
                        .IsUnique();

                    b.ToTable("group_event", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Groups.GroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("UserId");

                    b.ToTable("group_member", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Presets.LocationPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Coordinates", "Hub.Domain.Presets.LocationPreset.Coordinates#Coordinates", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<double>("Latitude")
                                .HasColumnType("double precision");

                            b1.Property<double>("Longitude")
                                .HasColumnType("double precision");
                        });

                    b.HasKey("Id");

                    b.ToTable("location_preset", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Presets.RequirementPreset", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("requirement_preset", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nickname")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Nickname")
                        .IsUnique();

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirementParticipantVerification", b =>
                {
                    b.HasBaseType("Hub.Domain.Events.Requirements.EventRequirementVerification");

                    b.Property<Guid>("VerifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_participant_id");

                    b.HasIndex("VerifiedById");

                    b.HasDiscriminator().HasValue("participant");
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirementRoleVerification", b =>
                {
                    b.HasBaseType("Hub.Domain.Events.Requirements.EventRequirementVerification");

                    b.Property<Guid>("VerifiedById")
                        .HasColumnType("uuid")
                        .HasColumnName("verified_by_role_id");

                    b.HasIndex("VerifiedById");

                    b.HasDiscriminator().HasValue("role");
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirementParticipantVerifier", b =>
                {
                    b.HasBaseType("Hub.Domain.Events.Requirements.EventRequirementVerifier");

                    b.Property<Guid>("VerifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("verifier_participant_id");

                    b.HasIndex("VerifierId");

                    b.HasDiscriminator().HasValue("participant");
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirementRoleVerifier", b =>
                {
                    b.HasBaseType("Hub.Domain.Events.Requirements.EventRequirementVerifier");

                    b.Property<Guid>("VerifierId")
                        .HasColumnType("uuid")
                        .HasColumnName("verifier_role_id");

                    b.HasIndex("VerifierId");

                    b.HasDiscriminator().HasValue("role");
                });

            modelBuilder.Entity("Hub.Domain.Events.EventLocation", b =>
                {
                    b.HasOne("Hub.Domain.Events.Event", "Event")
                        .WithOne("Location")
                        .HasForeignKey("Hub.Domain.Events.EventLocation", "EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Hub.Domain.Events.EventRole", b =>
                {
                    b.HasOne("Hub.Domain.Events.Event", "Event")
                        .WithMany("Roles")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Hub.Domain.Events.Goals.EventGoal", b =>
                {
                    b.HasOne("Hub.Domain.Events.Event", "Event")
                        .WithMany("Goals")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Hub.Domain.Events.Goals.EventGoalTask", b =>
                {
                    b.HasOne("Hub.Domain.Events.Goals.EventGoal", "Goal")
                        .WithMany("Tasks")
                        .HasForeignKey("GoalId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Goal");
                });

            modelBuilder.Entity("Hub.Domain.Events.Goals.EventGoalTaskAssignment", b =>
                {
                    b.HasOne("Hub.Domain.Events.Participants.EventParticipant", "ParticipantAssignment")
                        .WithMany("Tasks")
                        .HasForeignKey("ParticipantAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hub.Domain.Events.Goals.EventGoalTask", "Task")
                        .WithMany("Assignments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ParticipantAssignment");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Hub.Domain.Events.Participants.EventParticipant", b =>
                {
                    b.HasOne("Hub.Domain.Events.Event", "Event")
                        .WithMany("Participants")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hub.Domain.User", "User")
                        .WithMany("Participants")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hub.Domain.Events.Participants.EventParticipantRole", b =>
                {
                    b.HasOne("Hub.Domain.Events.Participants.EventParticipant", "Participant")
                        .WithMany("Roles")
                        .HasForeignKey("ParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hub.Domain.Events.EventRole", "Role")
                        .WithMany("Participants")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Participant");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirement", b =>
                {
                    b.HasOne("Hub.Domain.Events.Event", "Event")
                        .WithMany("Requirements")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirementAssignment", b =>
                {
                    b.HasOne("Hub.Domain.Events.Participants.EventParticipant", "AssignParticipant")
                        .WithMany("Requirements")
                        .HasForeignKey("AssignParticipantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hub.Domain.Events.Requirements.EventRequirement", "Requirement")
                        .WithMany("Assignments")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AssignParticipant");

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirementVerification", b =>
                {
                    b.HasOne("Hub.Domain.Events.Requirements.EventRequirementAssignment", "RequirementAssignment")
                        .WithMany("Verifications")
                        .HasForeignKey("RequirementAssignmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hub.Domain.Events.Requirements.EventRequirementVerifier", "Verifier")
                        .WithMany("Verifications")
                        .HasForeignKey("VerifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("RequirementAssignment");

                    b.Navigation("Verifier");
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirementVerifier", b =>
                {
                    b.HasOne("Hub.Domain.Events.Requirements.EventRequirement", "Requirement")
                        .WithMany("Verifiers")
                        .HasForeignKey("RequirementId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Requirement");
                });

            modelBuilder.Entity("Hub.Domain.Groups.GroupEvent", b =>
                {
                    b.HasOne("Hub.Domain.Events.Event", "Event")
                        .WithMany("GroupEvents")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hub.Domain.Groups.Group", "Group")
                        .WithMany("GroupEvents")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");

                    b.Navigation("Group");
                });

            modelBuilder.Entity("Hub.Domain.Groups.GroupMember", b =>
                {
                    b.HasOne("Hub.Domain.Groups.Group", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Hub.Domain.User", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirementParticipantVerification", b =>
                {
                    b.HasOne("Hub.Domain.Events.Participants.EventParticipant", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirementRoleVerification", b =>
                {
                    b.HasOne("Hub.Domain.Events.Participants.EventParticipantRole", "VerifiedBy")
                        .WithMany()
                        .HasForeignKey("VerifiedById")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("VerifiedBy");
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirementParticipantVerifier", b =>
                {
                    b.HasOne("Hub.Domain.Events.Participants.EventParticipant", "Verifier")
                        .WithMany()
                        .HasForeignKey("VerifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verifier");
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirementRoleVerifier", b =>
                {
                    b.HasOne("Hub.Domain.Events.EventRole", "Verifier")
                        .WithMany()
                        .HasForeignKey("VerifierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Verifier");
                });

            modelBuilder.Entity("Hub.Domain.Events.Event", b =>
                {
                    b.Navigation("Goals");

                    b.Navigation("GroupEvents");

                    b.Navigation("Location");

                    b.Navigation("Participants");

                    b.Navigation("Requirements");

                    b.Navigation("Roles");
                });

            modelBuilder.Entity("Hub.Domain.Events.EventRole", b =>
                {
                    b.Navigation("Participants");
                });

            modelBuilder.Entity("Hub.Domain.Events.Goals.EventGoal", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Hub.Domain.Events.Goals.EventGoalTask", b =>
                {
                    b.Navigation("Assignments");
                });

            modelBuilder.Entity("Hub.Domain.Events.Participants.EventParticipant", b =>
                {
                    b.Navigation("Requirements");

                    b.Navigation("Roles");

                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirement", b =>
                {
                    b.Navigation("Assignments");

                    b.Navigation("Verifiers");
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirementAssignment", b =>
                {
                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("Hub.Domain.Events.Requirements.EventRequirementVerifier", b =>
                {
                    b.Navigation("Verifications");
                });

            modelBuilder.Entity("Hub.Domain.Groups.Group", b =>
                {
                    b.Navigation("GroupEvents");

                    b.Navigation("Members");
                });

            modelBuilder.Entity("Hub.Domain.User", b =>
                {
                    b.Navigation("Memberships");

                    b.Navigation("Participants");
                });
#pragma warning restore 612, 618
        }
    }
}
